language: node_js
node_js:
- '6'
env:
  global:
    - secure: "l8Yq+iP44V2Vdm85YDLosDdKVQHFDzjDX7BY6CMJTuSeOIw5naICzQdGN0JH3ZZeTLI0gulWHpHA6yAVQyfYXxyDg8aRojYDORU7lyx3KrVvCq3SCkihWdGotQ+FF4v8A7kc6BeBsVLxK6uYH4RnXhr0Xlm+KJW1PEd/ZjTW93Es+tzWB5qL+IPGpJgzyDBY/Sa5bcgC0PhQvQUWZYD2UEuwrS1GJpQ2GZNzE8GshfP2oArHFQf4QdRUoDHDeGmb2BFuP6eD64ZHz1g6rv1S71QhmjnKkHpxbvNAUpQLGjCrOjuRJHuxfdM1pIKLWsaEY2b4Gue4sVwPp3w0Xm61RPpEQ18L1JZ125XVqV1JoDSZntX0+vavJaPPAKlyW8ezWAnj+MxlozF/PM8jGTye/4QmdAMrP/5ZbiEiBFbaKF01poIayijj0CaELMJaGA9gAIJoxcS4XjzqbE/uG4a66oK9ESno80kxLvT2FKppfbRnQHaBJN1CpSnECqtdBeMSxcQ86WBuugZ4OnwTvtJK2lJFGBiI+ee+0ZFJXyT/lNukGgRMIIs3btuLyJf07qcc+P7ZJu1jTdlAnA6DWS3Xk7MvIJGijoVJwFPJgBW2XHSD5sLLEyKEyeLpUpeT0elV8rSncx7nc/bGVMBS9UkSTp7XcDZAz64aTTCKuCkuzX8="
