language: node_js
node_js:
- '6'
env:
  global:
    - secure: WZe162NHrSfsJE/hE2yxnG/D8EqySlGSiOEuXeDeFjQvkXo7zAvVqb3LRUBmEpGZ/YMaMZPLZUFIfeAIsizSbirKZdi9Oj0IxGInl5pkf+ecm9k5LLSK+8R6G5J69r9FOXM833IiF/7D7T+fQBH8YATwy5jyxvhf7S6lHPZrM4MrLu6H81t2C/WkJJjy92/FTD/SYHCLfrxwX+a60H9PWYxd3Id0Tc3d6UOe/STpKXBBQSled1zpM11EvR2FvUSDMm2bwA4tISk1sVsHaeJyoUORdwMXKOxTQmwGhNAiZPHRcFDL9RoiA2AU9fuHTmxSQCyzICUECWrYihyfKaT28adx19MskOayThAEhAD53amN4O6gwtnzHVAy4KFeOKhITBpR6ldVRCotEXpABq9Uvvz7ijkidvpXttiXu+o9p1BK65v8WfQVpmAA1aPv37UaDFYeDqxKQrhfIqvZMesuWPsBeorztPp9Jj+4hsE6vBR4wk/OtCrh0JLOV2qAsYUDq17AIw1CiyffTKN9faAWnYx4WuKz9dSPbREwflFA3j0Qmu3ucIOffWXKw74Ji9eLhsgUKciozLnSVEAsJHyc1aNHALq6SoB9YJFhu9kpCxH/vej2GZ/843VxjeQ635CAjJCWiDn4qnv5JRPkcPccX69TkshBCy8XRXoKOx+nuVA=
